### ISSUE TITLE
[feat] Create "Lastest results component"

### ISSUE THREAD

**Issue by jsandinoDev** [Chonete-Builders/Starkcade#14]

**Comment by sonkeydotcom** [comment]
Can I take this issue?

**Comment by PrathamJha1** [comment]
Would love to contribute here , given my experience as a JavaScript and Typescript developer working in the Web3 space for over a year. Would need issue description in more details to get started

**Comment by aidenwong812** [comment]
I'd be happy to do this.

**Comment by Ekene001** [comment]
Could I take over this issue? I’m a full-stack blockchain developer with over 3 years of experience working with Tailwind, React, TypeScript, and Solidity/Rust.

**Comment by chiscookeke11** [comment]
I’d like to resolve this.
